version: '3'
services:
  bot:
      build: .
      ports:
        - "3000:3000"
      env_file:
        - "dev.env"
      environment:
        - NODE_ENV=production
      restart: on-failure:3
  redis:
    image: "redis:alpine"
    volumes:
      - ./data:/data
    restart: on-failure
